In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('C:\Kate\Python\ClaimPrediction\Data\\fdata_v1.csv', index_col=None)

In [5]:
dataset.head(10)

,hasclaim,modelscore,postalcodescore,external_make,external_model,external_engine,external_length_in,external_width_in,external_height_in,external_vinyear,...,viol_last_infractionage,acci_last_infractionage,viol_last_convictionage,acci_last_convictionage,birthdt,driverage,licensedt,havelicenseage,mvrstatusdt,mvrstatusage
0,0,0.280,0.231,Acura,TL,3.2,192.9,70.3,56.1,2000,...,0,0,0,0,1956-05-28T00:00:00.0000000,61,1972-05-28T00:00:00.0000000,16,2017-05-02T00:00:00.0000000,0
1,0,0.280,0.218,Acura,TL,3.2,189.3,72.2,56.7,2006,...,0,0,0,0,1993-10-11T00:00:00.0000000,18,2009-06-11T00:00:00.0000000,16,2011-08-31T00:00:00.0000000,0
2,1,0.258,0.217,Honda,Civic,1.8,177.3,69.0,56.5,2012,...,0,0,0,0,1986-07-16T00:00:00.0000000,27,2002-09-29T00:00:00.0000000,16,2012-07-10T00:00:00.0000000,1
3,0,0.258,0.344,Honda,Civic,1.8,177.3,69.0,56.5,2012,...,7,0,2,0,1953-09-26T00:00:00.0000000,63,1970-09-26T00:00:00.0000000,17,2015-11-18T00:00:00.0000000,1
4,0,0.276,0.229,Dodge,Stratus,2.4,191.2,70.6,54.9,2004,...,0,0,0,0,1974-10-05T00:00:00.0000000,35,1992-10-05T00:00:00.0000000,18,1900-01-01T00:00:00.0000000,0
5,0,0.276,0.235,Dodge,Intrepid,3.3,201.8,74.4,56.3,1996,...,0,0,0,0,1983-04-16T00:00:00.0000000,27,1999-05-06T00:00:00.0000000,16,1900-01-01T00:00:00.0000000,0
6,0,0.249,0.216,Dodge,Durango,4.7,193.3,71.5,72.9,2000,...,0,0,0,0,1971-05-21T00:00:00.0000000,44,1987-05-30T00:00:00.0000000,16,2013-05-30T00:00:00.0000000,2
7,0,0.276,0.252,Dodge,Dakota,3.9,214.8,71.5,65.6,2001,...,0,0,0,0,1967-08-23T00:00:00.0000000,44,1983-08-29T00:00:00.0000000,16,1900-01-01T00:00:00.0000000,0
8,0,0.274,0.209,Dodge,Ram 2500,8.0,244.0,79.3,72.8,1996,...,0,0,0,0,1994-10-24T00:00:00.0000000,22,2010-10-24T00:00:00.0000000,16,2016-04-14T00:00:00.0000000,0
9,0,0.280,0.247,Acura,TL,3.2,192.9,70.3,56.1,2001,...,0,0,0,0,1944-10-20T00:00:00.0000000,71,1960-10-20T00:00:00.0000000,16,2015-04-02T00:00:00.0000000,0

In [4]:
categorical_to_encode = [ 'external_make',
 'external_model',
 'postalcode',
 'city',
 'manufacturer',
 'model',
 'registrationstateprovcd',
 'vehbodytypecd',
 'performancecd',
 'restraintcd',
 'antibrakingsystemcd',
 'antitheftcd',
 'enginecylinders',
 'enginetype',
 'vehusecd',
 'classcd',
 'leasedvehind',
 'statedamtind',
 'neworusedind',
 'carpoolind',
 'daylightrunninglightsind',
 'passiveseatbeltind',
 'customizingequipmentind',
 'programtypecd',
 'mileage',
 'driverstatuscd',
 'licensedstateprovcd',
 'relationshiptoinsuredcd',
 'scholasticdiscountind',
 'mvrrequestind',
 'mvrstatus',
 'maturedriverind',
 'drivertrainingind',
 'gooddriverind',
 'accidentpreventioncourseind',
 'newtostateind',
 'persontypecd',
 'gendercd',
 'maritalstatuscd',
 'occupationclasscd'
]

In [6]:
for c in categorical_to_encode:
    dataset['%s_encd'%c] = pd.Categorical(dataset[c]).codes

In [7]:
dataset.head(10)

,hasclaim,modelscore,postalcodescore,external_make,external_model,external_engine,external_length_in,external_width_in,external_height_in,external_vinyear,...,mvrstatus_encd,maturedriverind_encd,drivertrainingind_encd,gooddriverind_encd,accidentpreventioncourseind_encd,newtostateind_encd,persontypecd_encd,gendercd_encd,maritalstatuscd_encd,occupationclasscd_encd
0,0,0.280,0.231,Acura,TL,3.2,192.9,70.3,56.1,2000,...,3,0,3,2,2,2,0,1,0,10853
1,0,0.280,0.218,Acura,TL,3.2,189.3,72.2,56.7,2006,...,0,0,3,0,2,2,0,1,1,9472
2,1,0.258,0.217,Honda,Civic,1.8,177.3,69.0,56.5,2012,...,1,0,3,2,2,2,0,0,1,8439
3,0,0.258,0.344,Honda,Civic,1.8,177.3,69.0,56.5,2012,...,0,0,3,2,2,2,0,1,0,8693
4,0,0.276,0.229,Dodge,Stratus,2.4,191.2,70.6,54.9,2004,...,4,0,1,2,0,2,0,0,1,2378
5,0,0.276,0.235,Dodge,Intrepid,3.3,201.8,74.4,56.3,1996,...,4,0,1,2,0,2,0,0,1,10286
6,0,0.249,0.216,Dodge,Durango,4.7,193.3,71.5,72.9,2000,...,1,0,3,2,2,2,0,0,0,3763
7,0,0.276,0.252,Dodge,Dakota,3.9,214.8,71.5,65.6,2001,...,4,0,1,2,0,2,0,0,1,765
8,0,0.274,0.209,Dodge,Ram 2500,8.0,244.0,79.3,72.8,1996,...,3,0,3,2,2,2,0,1,1,10300
9,0,0.280,0.247,Acura,TL,3.2,192.9,70.3,56.1,2001,...,1,0,1,2,0,2,0,0,0,8199

In [8]:
dataset.to_csv('C:\Kate\Python\ClaimPrediction\Data\\fdata_v1_encd.csv')